# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "erl"
license = "MIT"
licenselink = "https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/LICENSE.md"
description = "erl theme"
homepage = "https://cfreeman.github.io/erl/"
tags = ["website", "starter", "responsive"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.55.0"

[author]
  name = "reprage"
  homepage = "https://reprage.com/"
